#!/usr/bin/env python3
from sys import argv
from pathlib import Path

DAY = argv[1]

# Create dir for day
dir_path = Path(f'day0{DAY}')

if not dir_path.exists():
    dir_path.mkdir()

# Create file paths
file_paths = {
    "input_file": dir_path / 'input.txt',
    "sol_file"  : dir_path / 'solution.cpp',
    "sol_h_file": dir_path / 'solution.h',
    "test_file" : dir_path / 'tests.cpp',
    "test_part1": dir_path / 'test1.txt',
    "test_part2": dir_path / 'test2.txt'
}

# Create file
for file_path in file_paths.values():
    if not file_path.exists():
        file_path.touch()


# Create test file boiler plate code
with file_paths["test_file"].open('w') as f:
    f.write('''#include <gtest/gtest.h>
#include "solution.h"


TEST(SUITE_NAME, TEST_NAME) {
   ASSERT_EQ(5, 5);
}


int main(int argc, char **argv) {
   testing::InitGoogleTest(&argc, argv);

   if (RUN_ALL_TESTS() == 0) {
      std::cout << "All tests passed.\\n";
   }

   init();
   return 0;
}
''')


with file_paths["sol_h_file"].open("w") as f:
    f.write('''
#pragma once
#include <vector>
#include <map>

using namespace std;

void init();
void printVector(std::vector<long>& v);
''')

with file_paths["sol_file"].open("w") as f:
    f.write('''#include <iostream>
#include <map>
#include <string>
#include <fstream>
#include <algorithm>
#include "../file_utils.h"
#include "solution.h"

using namespace std;

void init() {
    std::vector<std::vector<long> > inp;
    // CHANGE THE DAY!
    FileUtils::read_as_list_of_split_longs("day0/input.txt", inp, ',', '"', '#');
    cout << "From solution file\\n";

    // vector<long> exp{};

    // ifstream f{"day0/input.txt"};
    // string buf;

    // while (getline(f, buf)) {
        // exp.push_back(stol(buf));
    // }
}


/** To  */
void printVector(std::vector<long>& v) {
    for (auto const &n: v) {
        std::cout << n << " ";
    }
    std::cout << std::endl;
}
''')